### ISSUE TITLE
Github actions

### ISSUE THREAD

**Issue by Dougniel** [opt-nc/opt-temps-attente-agences-sdk#1]
- [x] Build maven en CI
- [x] Scan CodeQL
- [x] Build Matrix openjdk-java : 8,11,13

**Comment by Dougniel** [comment]
@adriens , je crois que j'ai des soucis de droits pour pouvoir publier dans le repo maven
J'ai fait la même chose qu'avec api-mobilis-partenaires et ça marche pas

**Comment by adriens** [comment]
je check ça ⚡

**Comment by adriens** [comment]
pourtant tout le GLIA est en maintainer ;-(

**Comment by adriens** [comment]
![image](https://user-images.githubusercontent.com/5235127/131460019-68273ad0-615c-404c-ab06-7479e2691b0c.png)

**Comment by adriens** [comment]
Ce serait pas à `bot-ci` de faire ce boulot d'ailleurs @mbarre  ❔

**Comment by adriens** [comment]
Car là, les privilèges sont déja au plus haut, ie. maintainer... il faudrait pas être owner, c'est dangereux et overkill 😈

**Comment by Dougniel** [comment]
@adriens , par rapport à l'erreur https://github.com/opt-nc/opt-temps-attente-agences-sdk/issues/1#issuecomment-908968374, il faudrait supprimer l'artefact [ici](https://github.com/opt-nc/opt-temps-attente-agences-sdk/packages), moi je n'ai pas le droit

**Comment by Dougniel** [comment]
Retour sur jitpack.io 👍
