### ISSUE TITLE
Déploiement dans le repo maven GH

### ISSUE THREAD

**Issue by Dougniel** [opt-nc/opt-temps-attente-agences-sdk#11]

**Comment by Dougniel** [comment]
@adriens, est-ce que tu pourrais regarder dans la conf global de dependabot s'il a bien accès aux tokens https://github.community/t/dependabot-is-not-showing-updates-from-public-github-registry/133377/8 stp ?

Car j'ai une erreur lorsqu'il essaye d'accéder au maven regisry du sdk https://github.com/opt-nc/opt-temps-attente-agences-api/network/updates/235296682

**Comment by adriens** [comment]
> y'a pas de conf globale

est-ce que tu pourrais regarder dans la conf global de dependabot s'il a bien accès aux tokens 

Pour le SDK de cette lib Open Source, privilégier Jitpack afin que nous soyons dans le même cas de figure que l'API et nos users finaux 🙏

**Comment by Dougniel** [comment]
https://github.com/opt-nc/opt-temps-attente-agences-sdk/commit/6441733dc754b46430e0d1d69c4f81228835cbf2
