### ISSUE TITLE
Conflit `Logback` 

### ISSUE THREAD

**Issue by Dougniel** [opt-nc/opt-temps-attente-agences-sdk#49]
A priori, cela vient d'une dépendance de logging mal choisi pour une lib (utilisation d'une implémentation au lieu d'une façade)

_Originally posted by @Dougniel in https://github.com/opt-nc/opt-temps-attente-agences-api/issues/113#issuecomment-1418427067_

**Comment by Dougniel** [comment]
Bon les tests unitaires ne passent plus alors qu'il n'y a pas de code qui a changé depuis 🤨

**Comment by adriens** [comment]
> utilisation d'une implémentation au lieu d'une façade)

C'est mal 💩

**Comment by adriens** [comment]
:zap:

**Comment by Dougniel** [comment]
D'ici on ne voit pas toutes les erreurs dans la CI, c'est pas terminé mais le ticket switch automatiquement

**Comment by Dougniel** [comment]
Cette fois-ci c'est bon : ![build](https://github.com/opt-nc/opt-temps-attente-agences-sdk/actions/workflows/maven.yml/badge.svg)
